# Generated by Django 4.2.30 on 2026-06-11 20:31

import authentication.managers
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("username", models.CharField(max_length=255, unique=True)),
                ("bio", models.TextField(blank=True, default="")),
                ("image", models.CharField(blank=True, default="", max_length=511)),
            ],
            options={
                "db_table": "users",
            },
            managers=[
                ("objects", authentication.managers.UserManager()),
            ],
        ),
    ]
