app.logging.http.include-headers=false
app.logging.http.include-payload=false
app.logging.service.enabled=false
logging.level.io.spring.http=INFO
logging.level.io.spring.infrastructure.mybatis=WARN
logging.level.io.spring.infrastructure.mybatis.readservice.ArticleReadService=WARN
logging.level.io.spring.infrastructure.mybatis.mapper=WARN
