spring.datasource.url=jdbc:tc:postgresql:14-alpine:///realworld_test
spring.datasource.driver-class-name=org.testcontainers.jdbc.ContainerDatabaseDriver
spring.datasource.username=test
spring.datasource.password=test

spring.flyway.locations=classpath:db/migration/postgresql
